name: Build and deploy to Artifact registry
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}
        #   project_id: "infra-massivepixel"
        #   workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"

      - name: Register gcloud as a Docker credential helper
        run: gcloud auth configure-docker
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: europe-docker.pkg.dev/infra-massivepixel/containers/gha-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
